version : "3"

services :
        app:
               build:
                       context: ./01_FLASK_DOCKER
                       dockerfile: Dockerfile
               links:
                       - "db:mysqldb"
               ports:
                       - "80:8080"
               container_name: appcontainer
               depends_on :
                       - db
        db:
                image: mysql:5.7
                volumes :
                        - ./mysqldata:/var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=jjcoding
                        - MYSQL_DATABASE=jjdb
                ports:
                        - "3306:3306"
                container_name: dbcontainer
